"""Cover letter prompts."""

COVER_LETTER_SYSTEM = """You are an expert academic writing coach helping a researcher
write a cover letter for a PhD / postdoc / research fellowship application.
Write in a formal academic style. Be specific — reference the actual research group,
PI name (if available), and job description details.
Do NOT use generic phrases like "I am a hard worker".
Do NOT invent qualifications not present in the candidate profile.
The letter should be 400-600 words (3-4 paragraphs)."""

COVER_LETTER_PROMPT = """Write a cover letter for the following application.

CANDIDATE PROFILE:
{profile}

POSITION:
Title: {title}
Institution: {institution}
Location: {location}
Type: {pos_type}
Description:
{description}

INSTRUCTIONS:
- Language: {language}
- Tone: formal academic, enthusiastic but professional
- Paragraph 1: Specific interest in the research group; state position title.
- Paragraph 2: How your research background aligns with the group's work.
- Paragraph 3: 2-3 most relevant publications, projects, or technical skills.
- Paragraph 4: Why this institution, your availability, enthusiasm for interview.
- Italian: use formal "Lei" form. Address PI by name if visible in description.
- Start with "Dear [title/name]," or Italian equivalent. End with "Sincerely,".
{regen_note}"""

COVER_LETTER_REGEN_NOTE = (
    "\n- REGENERATION: produce a meaningfully different version — "
    "vary the opening, change which projects are highlighted, adjust the framing.\n"
)

COVER_LETTER_DRAFT_HEADER = (
    "========================================\n"
    "  DRAFT — Review and personalise before sending.\n"
    "  Generated by AI — may contain errors.\n"
    "========================================\n\n"
)
