"""Cover letter generator for research/PhD/postdoc applications."""

from __future__ import annotations

from typing import Any

from agent.base_service import BaseLLMService
from agent.llm_client import LLMQuotaError
from agent.utils import job_description, job_institution

_ITALIAN_KEYWORDS = {
    "ricerca", "lavoro", "azienda", "esperienza", "candidato", "assunzione",
    "offerta", "contratto", "sede", "università", "bando", "dottorato",
    "assegno di ricerca", "borsa", "ricercatore",
    "Milano", "Roma", "Torino", "Napoli", "Firenze", "Bologna", "Italia",
}

_SYSTEM = """You are an expert academic writing coach helping a researcher
write a cover letter for a PhD / postdoc / research fellowship application.
Write in a formal academic style. Be specific — reference the actual research group,
PI name (if available), and job description details.
Do NOT use generic phrases like "I am a hard worker".
Do NOT invent qualifications not present in the candidate profile.
The letter should be 400-600 words (3-4 paragraphs)."""

_PROMPT = """Write a cover letter for the following application.

CANDIDATE PROFILE:
{profile}

POSITION:
Title: {title}
Institution: {institution}
Location: {location}
Type: {pos_type}
Description:
{description}

INSTRUCTIONS:
- Language: {language}
- Tone: formal academic, enthusiastic but professional
- Paragraph 1: Specific interest in the research group; state position title.
- Paragraph 2: How your research background aligns with the group's work.
- Paragraph 3: 2-3 most relevant publications, projects, or technical skills.
- Paragraph 4: Why this institution, your availability, enthusiasm for interview.
- Italian: use formal "Lei" form. Address PI by name if visible in description.
- Start with "Dear [title/name]," or Italian equivalent. End with "Sincerely,".
{regen_note}"""

_REGEN_NOTE = (
    "\n- REGENERATION: produce a meaningfully different version — "
    "vary the opening, change which projects are highlighted, adjust the framing.\n"
)

_DRAFT_HEADER = (
    "========================================\n"
    "  DRAFT — Review and personalise before sending.\n"
    "  Generated by AI — may contain errors.\n"
    "========================================\n\n"
)


class CoverLetterWriter(BaseLLMService):
    """Generates DRAFT cover letters for research positions."""

    _SYSTEM = _SYSTEM

    def generate(
        self,
        job: dict[str, Any],
        profile_text: str,
        regenerate: bool = False,
    ) -> str:
        """Generate a draft cover letter prefixed with a DRAFT notice.

        LLMQuotaError propagates — it must be surfaced to the user.
        Other LLM errors return a graceful error string.
        """
        language = self._detect_language(job)
        prompt = _PROMPT.format(
            profile=profile_text,
            title=job.get("title", "Unknown Position"),
            institution=job_institution(job) or "Unknown Institution",
            location=job.get("location", "Unknown"),
            pos_type=job.get("type", "research"),
            description=job_description(job),
            language=language,
            regen_note=_REGEN_NOTE if regenerate else "",
        )

        try:
            letter = self._generate(prompt)
        except LLMQuotaError:
            raise
        except RuntimeError as exc:
            return (
                "[DRAFT — GENERATION FAILED]\n\n"
                f"Error: {exc}\n\n"
                "Please write your cover letter manually."
            )

        return _DRAFT_HEADER + letter.strip()

    @staticmethod
    def _detect_language(job: dict[str, Any]) -> str:
        text = " ".join([
            job.get("title", ""),
            job.get("description", ""),
            job.get("location", ""),
            job_institution(job),
        ]).lower()
        hits = sum(1 for kw in _ITALIAN_KEYWORDS if kw.lower() in text)
        return "Italian" if hits >= 2 else "English"
